import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect , useState } from "react";

const RickandMorty = 'https://jsonplaceholder.typicode.com/users';

export const getStaticProps = async () => {
  const res = await fetch(RickandMorty);
  const data = await res.json(); // returns data from the api
  

  return {
    props: {  ninjas : data}
  };
}

const  Home = ({ ninjas }) => {
  //const [Post , setPost ] = useState([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Learning APIs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



     <main className={styles.main}>
     <h1 className={styles.title}>Static</h1>

     <p className={styles.description}>static text</p>

        <ul className={styles.grid}>
        
        {ninjas.map(ninja =>(
          <li key={ninja.id} className={styles.card}>
          <a href="https://nextjs.org/docs" >
            <h2>Static looped && {ninja.name}</h2>
            <p>{ninja.email}</p>
            <p>{ninja.username}</p>
            <p>{ninja.phone}</p>
            <p>{ninja.address.street}</p>
          </a>
          </li>
         
          ))} 
        </ul>
      </main>

     
    </div>
  );
}
export default Home;